# Exported from Render on 2024-03-24T21:50:18Z
# https://msfish.onrender.com
services:
- type: web
  name: msfish
  runtime: node
  repo: https://github.com/ddupas/msfish
  branch: main
  plan: free
  envVars:
  - key: pm2.link.secret.sh
    sync: false
  - key: known_hosts
    sync: false
  - key: id_ed25519
    sync: false
  - key: config.json
    sync: false
  region: oregon
  buildCommand: bun i
  startCommand: bun run discord-bot & bun run msfish & bun run http-server
  autoDeploy: false
version: "1"
